use  school;
select * from employees;
select emp_id,first_name from employees where first_name like 'su%'; 
select (count(salary)) from employees;
select * from employees where first_name like 's%' or salary>25000;
select * from employees where first_name like 's%' and salary>25000;
select first_name from employees where salary>=20000 and salary< 30000;
select last_name from employees where salary>=20000 or salary<300000;
select first_name,last_name from employees where salary between 25000 and 30000;
select first_name from employees where last_name like 's%';
select * from employees where salary in (23000,34000,24000);
select first_name from employees where salary is not null;
select (count(salary)) from employees;
select emp_id,first_name from employees order by salary;
alter table employees add column dept varchar(20);
describe employees;
update employees set dept='sales' where emp_id=001;
update employees set dept='finance' where emp_id=002;
update employees set dept='marketing' where emp_id=003;
update employees set dept='marketing' where emp_id=004;
update employees set dept='sales' where emp_id=005;
update employees set dept='finance' where emp_id=006;
update employees set dept='sales' where emp_id=007;
update employees set dept='marketing' where emp_id=008;
select dept,first_name from employees;
select emp_id,first_name,last_name,max(salary) from employees group by dept;
select emp_id,first_name,last_name,min(salary) from employees group by dept;
select emp_id ,max(salary) from employees group by dept;
select emp_id,first_name,last_name  from employees;
select emp_id,first_name,last_name,max(salary) from employees group by dept having count(dept)>2;